language: cpp

matrix:
  include:
    - compiler: gcc
      env: CONFIG=release_x64
      addons:
        apt:
          sources:
            - boost-latest
            - llvm-toolchain-precise-3.7
            - ubuntu-toolchain-r-test
          packages:
            - g++-5-multilib
            - gcc-5-multilib
            - libboost1.55-all-dev
            - php5-cli

    # - compiler: gcc
    #   env: CONFIG=release_x32
    #   addons:
    #     apt:
    #       sources:
    #         - boost-latest
    #         - llvm-toolchain-precise-3.7
    #         - ubuntu-toolchain-r-test
    #       packages:
    #         - cpp-4.6
    #         - g++-5-multilib
    #         - gcc-5-multilib
    #         - linux-libc-dev:i386
    #         - libboost-all-dev:i386
    #         - php5-cli

    - compiler: clang
      env: CONFIG=release_x64
      addons:
        apt:
          sources:
            - boost-latest
            - llvm-toolchain-precise-3.7
            - ubuntu-toolchain-r-test
          packages:
            - clang-3.7
            - libboost1.55-all-dev
            - php5-cli

    # - compiler: clang
    #   env: CONFIG=release_x32
    #   addons:
    #     apt:
    #       sources:
    #         - boost-latest
    #         - llvm-toolchain-precise-3.7
    #         - ubuntu-toolchain-r-test
    #       packages:
    #         - cpp-4.6
    #         - clang-3.7
    #         - linux-libc-dev:i386
    #         - libboost-all-dev:i386
    #         - php5-cli

before_install:
  # Download and build premake5 from source; the Travis environment doesn't have the right version of glibc6 for the prebuilt binaries to work.
  - wget https://github.com/premake/premake-core/releases/download/v5.0.0-alpha6/premake-5.0.0-alpha6-src.zip -O premake.zip
  - unzip premake.zip
  - cd premake-5.0.0-alpha6/build/gmake.unix
  - make config=release
  - cd ../../..
  - sudo mv premake-5.0.0-alpha6/bin/release/premake5 /usr/bin
  # - mv premake-5.0.0-alpha6/bin/release/premake5 build/premake5

install:
    - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
    - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.7" CC="clang-3.7"; fi

before_script:
  - cd ${TRAVIS_BUILD_DIR}/thirdparty/ULib
  - ./configure --disable-shared
  - make
  - cd ${TRAVIS_BUILD_DIR}

script:
  - make CONFIG=$CONFIG
